# -*- coding: utf-8 -*-

alphabet = {
"'": u"   \n"
     u"██ \n"
     u" ▀ \n"
     u"   \n"
     u"   \n"
     u"   \n"
     u"   \n",
"\"":u"    \n"
     u"█ █ \n"
     u"▀ ▀ \n"
     u"    \n"
     u"    \n"
     u"    \n"
     u"    \n",
" ": u"   \n"
     u"   \n"
     u"   \n"
     u"   \n"
     u"   \n"
     u"   \n"
     u"   \n",
"-": u"    \n"
     u"    \n"
     u"    \n"
     u"    \n"
     u"███ \n"
     u"    \n"
     u"    \n",
".": u"   \n"
     u"   \n"
     u"   \n"
     u"   \n"
     u"   \n"
     u" █ \n"
     u"   \n",
":": u"   \n"
     u"   \n"
     u" █ \n"
     u"   \n"
     u"   \n"
     u" █ \n"
     u"   \n",
",": u"   \n"
     u"   \n"
     u"   \n"
     u"   \n"
     u"   \n"
     u" █ \n"
     u"▀  \n",
"/": u"     \n"
     u"    █\n"
     u"   █ \n"
     u"  █  \n"
     u" █   \n"
     u"█    \n"
     u"     \n",
"?": u"      \n"
     u"▄▀▀▀▄ \n"
     u"█   █ \n"
     u"   ▄▀ \n"
     u"  ▀   \n"
     u"  █   \n"
     u"      \n",
"!": u"  \n"
     u"█ \n"
     u"█ \n"
     u"█ \n"
     u"▀ \n"
     u"█ \n"
     u"  \n" ,
"1": u"    \n"
     u"▄▄  \n"
     u" █  \n"
     u" █  \n"
     u" █  \n"
     u"▄█▄ \n"
     u"    \n",
"2": u"     \n"
     u" ▄▄  \n"
     u"▀  █ \n"
     u"  ▄▀ \n"
     u"▄▀   \n"
     u"█▄▄▄ \n"
     u"     \n",
"3": u"     \n"
     u" ▄▄  \n"
     u"▀  █ \n"
     u" ▄▄█ \n"
     u"   █ \n"
     u"▀▄▄▀ \n"
     u"     \n",
"4": u"     \n"
     u"▄  ▄ \n"
     u"█  █ \n"
     u"▀▄▄█ \n"
     u"   █ \n"
     u"   █ \n"
     u"     \n",
"5": u"     \n"
     u"▄▄▄▄ \n"
     u"█    \n"
     u"▀▄▄▄ \n"
     u"   █ \n"
     u"▀▄▄▀ \n"
     u"     \n",
"6": u"     \n"
     u" ▄▄  \n"
     u"█  ▀ \n"
     u"█▄▄▄ \n"
     u"█  █ \n"
     u"▀▄▄▀ \n"
     u"     \n",
"7": u"     \n"
     u"▄▄▄▄ \n"
     u"   █ \n"
     u"  █  \n"
     u"  █  \n"
     u" █   \n"
     u"     \n",
"8": u"     \n"
     u" ▄▄  \n"
     u"█  █ \n"
     u"█▄▄█ \n"
     u"█  █ \n"
     u"▀▄▄▀ \n"
     u"     \n",
"9": u"     \n"
     u" ▄▄  \n"
     u"█  █ \n"
     u"▀▄▄█ \n"
     u"   █ \n"
     u"   █ \n"
     u"     \n",
"0": u"     \n"
     u" ▄▄  \n"
     u"█  █ \n"
     u"█ ▄█ \n"
     u"█▀ █ \n"
     u"▀▄▄▀ \n"
     u"     \n",
"a": u"     \n"
     u"     \n"
     u"     \n"
     u" ▄▄  \n"
     u"█  █ \n"
     u"▀▄▀█ \n"
     u"     \n" ,
"b": u"     \n"
     u"█    \n"
     u"█    \n"
     u"█▄▄  \n"
     u"█  █ \n"
     u"█▄▄▀ \n"
     u"     \n" ,
"c": u"     \n"
     u"     \n"
     u"     \n"
     u" ▄▄  \n"
     u"█  ▀ \n"
     u"▀▄▄▄ \n"
     u"     \n" ,
"d": u"     \n"
     u"   █ \n"
     u"   █ \n"
     u" ▄▄█ \n"
     u"█  █ \n"
     u"▀▄▄█ \n"
     u"     \n" ,
"e": u"     \n"
     u"     \n"
     u"     \n"
     u" ▄▄  \n"
     u"█▄▄▀ \n"
     u"▀▄▄▄ \n"
     u"     \n" ,
"f": u"    \n"
     u"▄█▀▀\n"
     u"█   \n"
     u"█▀▀ \n"
     u"█   \n"
     u"█   \n"
     u"    \n" ,
"g": u"     \n"
     u"     \n"
     u"     \n"
     u" ▄▄  \n"
     u"█  █ \n"
     u"▀▄▄█ \n"
     u"▄▄▄▀ \n" ,
"h": u"     \n"
     u"█    \n"
     u"█    \n"
     u"█▄▄  \n"
     u"█  █ \n"
     u"█  █ \n"
     u"     \n" ,
"i": u"  \n"
     u"  \n"
     u"  \n"
     u"▀ \n"
     u"█ \n"
     u"█ \n"
     u"  \n" ,
"j": u"   \n"
     u"   \n"
     u"   \n"
     u"\033[1D  ▀ \n"
     u"\033[1D  █ \n"
     u"\033[1D  █ \n"
     u"\033[1D▄▄▀ \n" ,
"k": u"     \n"
     u"█    \n"
     u"█    \n"
     u"█  ▄ \n"
     u"█▄▀  \n"
     u"█ ▀▄ \n"
     u"     \n" ,
"l": u"  \n"
     u"█ \n"
     u"█ \n"
     u"█ \n"
     u"█ \n"
     u"█ \n"
     u"  \n" ,
"m": u"      \n"
     u"      \n"
     u"      \n"
     u"▄▄ ▄  \n"
     u"█ █ █ \n"
     u"█ █ █ \n"
     u"      \n" ,
"n": u"     \n"
     u"     \n"
     u"     \n"
     u"▄▄▄  \n"
     u"█  █ \n"
     u"█  █ \n"
     u"     \n" ,
"o": u"     \n"
     u"     \n"
     u"     \n"
     u" ▄▄  \n"
     u"█  █ \n"
     u"▀▄▄▀ \n"
     u"     \n" ,
"p": u"     \n"
     u"     \n"
     u"     \n"
     u" ▄▄  \n"
     u"█  █ \n"
     u"█▄▄▀ \n"
     u"█    \n" ,
"q": u"     \n"
     u"     \n"
     u"     \n"
     u" ▄▄  \n"
     u"█  █ \n"
     u"▀▄▄█ \n"
     u"   █ \n" ,
"r": u"     \n"
     u"     \n"
     u"     \n"
     u"▄ ▄▄ \n"
     u"█▀ ▀ \n"
     u"█    \n"
     u"     \n" ,
"s": u"     \n"
     u"     \n"
     u"     \n"
     u" ▄▄▄ \n"
     u"▀▄▄▄ \n"
     u"▄▄▄▀ \n"
     u"     \n" ,
"t": u"    \n"
     u" █  \n"
     u" █  \n"
     u"▀█▀ \n"
     u" █  \n"
     u" █  \n"
     u"    \n" ,
"u": u"     \n"
     u"     \n"
     u"     \n"
     u"▄  ▄ \n"
     u"█  █ \n"
     u"▀▄▄█ \n"
     u"     \n" ,
"v": u"     \n"
     u"     \n"
     u"     \n"
     u"▄  ▄ \n"
     u"█  █ \n"
     u"▀▄▀  \n"
     u"     \n" ,
"w": u"      \n"
     u"      \n"
     u"      \n"
     u"▄   ▄ \n"
     u"█ █ █ \n"
     u"▀▄▀▄▀ \n"
     u"      \n" ,
"x": u"      \n"
     u"      \n"
     u"      \n"
     u"▄   ▄ \n"
     u" ▀▄▀  \n"
     u"▄▀ ▀▄ \n"
     u"      \n" ,
"y": u"     \n"
     u"     \n"
     u"     \n"
     u"▄  ▄ \n"
     u"█  █ \n"
     u"▀▄▄█ \n"
     u"▄▄▄▀ \n" ,
"z": u"     \n"
     u"     \n"
     u"     \n"
     u"▄▄▄▄ \n"
     u" ▄▄▀ \n"
     u"█▄▄▄ \n"
     u"     \n" }

